name: learn-github-actions
run-name: ${{ github.actor }} is learning github actions 
on: [push]
jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v4
     - uses: actions/setup-node@v3
       with:
        node-version: '18'
     - run: node -v
    
  job-2:
    runs-on: ubuntu-latest
    needs: job-1
    steps:
     - uses: actions/checkout@v4
     - uses: actions/setup-node@v3
       with:
        node-version: '18'
     - run: npm i nodemon 
