name: learn-github-actions
run-name: ${{ github.actor }} is learning github actions 
on: [push]
jobs:   
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
     - name: checkout code
       uses: actions/checkout@v4
     - name: build nodejs with docker
       run: docker build -t nodejs-image .
     - name: verification of images
       run: docker images 

       
